name: Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  release:
    name: Release

    permissions:
      id-token: write
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: current
          registry-url: https://registry.npmjs.org

      - name: Install required dependencies
        run: npm install

      - name: Publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
